spring.datasource.url: jdbc:h2:file:./camunda-h2-database
server:
  port: 8080
camunda.bpm.admin-user:
  id: admin
  password: admin
camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P1D
    client:
      base-url: http://localhost:8080/engine-rest

spring:
  kafka:
    bootstrap-servers: localhost:29092

